import Head from 'next/head'
import { useEffect, useState } from 'react'
import { client } from '../utils/client'

export default function Chat() {

  // const [showMessage, setShowMessage] = useState([])

  // useEffect(() => {
  //   const query = '*[_type == "message"]'

  //   client.fetch(query).then((data) => {
  //     setShowMessage(data)
  //   })

  // },[])

  const user ="loki"

  return (
    <>
      <Head>
        <title>Pocket Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='h-screen flex justify-center items-center flex-col'>
      <div>
      <h1 
      className='text-3xl font-bold lg:text-5xl py-6 text-gray-400 font-poppins uppercase tracking-[2px]'
      >
      Pocket chat
      </h1>
      </div>
      <div>
        <h1 className='text-md font-poppins capitalize tracking-[1px]'>logged in as {user}</h1>
      </div>
        {/* {
        showMessage.map((m) => {
          return(
            <div key={m._id}>
              <p>{m.message}</p>
            </div>
          )
        })
      } */}
    </div>
    </>
  )
}
